/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeterogeneousTargetApplyConfiguration represents a declarative configuration of the HeterogeneousTarget type for use
// with apply.
type HeterogeneousTargetApplyConfiguration struct {
	Params                   []HeterogeneousTargetParamApplyConfiguration `json:"params,omitempty"`
	CostExpansionRatePercent *int32                                       `json:"costExpansionRatePercent,omitempty"`
}

// HeterogeneousTargetApplyConfiguration constructs a declarative configuration of the HeterogeneousTarget type for use with
// apply.
func HeterogeneousTarget() *HeterogeneousTargetApplyConfiguration {
	return &HeterogeneousTargetApplyConfiguration{}
}

// WithParams adds the given value to the Params field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Params field.
func (b *HeterogeneousTargetApplyConfiguration) WithParams(values ...*HeterogeneousTargetParamApplyConfiguration) *HeterogeneousTargetApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParams")
		}
		b.Params = append(b.Params, *values[i])
	}
	return b
}

// WithCostExpansionRatePercent sets the CostExpansionRatePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CostExpansionRatePercent field is set to the value of the last call.
func (b *HeterogeneousTargetApplyConfiguration) WithCostExpansionRatePercent(value int32) *HeterogeneousTargetApplyConfiguration {
	b.CostExpansionRatePercent = &value
	return b
}
