/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MetricEndpointApplyConfiguration represents a declarative configuration of the MetricEndpoint type for use
// with apply.
type MetricEndpointApplyConfiguration struct {
	Uri           *string                             `json:"uri,omitempty"`
	Port          *int32                              `json:"port,omitempty"`
	LabelSelector *v1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
}

// MetricEndpointApplyConfiguration constructs a declarative configuration of the MetricEndpoint type for use with
// apply.
func MetricEndpoint() *MetricEndpointApplyConfiguration {
	return &MetricEndpointApplyConfiguration{}
}

// WithUri sets the Uri field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uri field is set to the value of the last call.
func (b *MetricEndpointApplyConfiguration) WithUri(value string) *MetricEndpointApplyConfiguration {
	b.Uri = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *MetricEndpointApplyConfiguration) WithPort(value int32) *MetricEndpointApplyConfiguration {
	b.Port = &value
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *MetricEndpointApplyConfiguration) WithLabelSelector(value *v1.LabelSelectorApplyConfiguration) *MetricEndpointApplyConfiguration {
	b.LabelSelector = value
	return b
}
